/**
 * --------------------------------------------------------------------------------------------------------
 *   Project                                            :               DREAM
 * --------------------------------------------------------------------------------------------------------
 *   File Name                                          :               DescribeResultAccessFault.java
 *   File Type                                          :               Source Code
 *   Description                                        :                *
 * --------------------------------------------------------------------------------------------------------
 *
 * =================================================================
 *             (coffee) COPYRIGHT EADS ASTRIUM LIMITED 2013. All Rights Reserved
 *             This software is supplied by EADS Astrium Limited on the express terms
 *             that it is to be treated as confidential and that it may not be copied,
 *             used or disclosed to others for any purpose except as authorised in
 *             writing by this Company.
 * --------------------------------------------------------------------------------------------------------
 */
package net.eads.astrium.hmas.exceptions;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2012-07-06T10:49:28.672+01:00
 * Generated source version: 2.6.1
 */

public class DescribeResultAccessFault extends OWSException {
    
    public DescribeResultAccessFault() {
        super();
    }
    
    public DescribeResultAccessFault(String message) {
        super(message);
    }
    
    public DescribeResultAccessFault(String message, Throwable cause) {
        super(message, cause);
    }

    public DescribeResultAccessFault(String message, net.opengis.ows.x11.ExceptionDocument exception) {
        super(message);
        this.exception = exception;
    }

    public DescribeResultAccessFault(String message, net.opengis.ows.x11.ExceptionDocument exception, Throwable cause) {
        super(message, cause);
        this.exception = exception;
    }

    public net.opengis.ows.x11.ExceptionDocument getFaultInfo() {
        return this.exception;
    }
}
